// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFileExplorer.Domain;

#nullable disable

namespace WebFileExplorer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230426210643_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebFileExplorer.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootFolderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RootFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resources",
                            RootFolderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evidence",
                            RootFolderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Graphic Products",
                            RootFolderId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Primary Sources",
                            RootFolderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Process",
                            RootFolderId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Final Product",
                            RootFolderId = 4
                        });
                });

            modelBuilder.Entity("WebFileExplorer.Models.Folder", b =>
                {
                    b.HasOne("WebFileExplorer.Models.Folder", "RootFolder")
                        .WithMany()
                        .HasForeignKey("RootFolderId");

                    b.Navigation("RootFolder");
                });
#pragma warning restore 612, 618
        }
    }
}
